[project]
name = "plant-gorithm"
version = "0.1.0"
description = "DATA440_Final"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dash>=3.0.3",
    "dash-bootstrap-components>=2.0.2",
    "pandas>=2.2.3",
    "openpyxl>=3.1.2"]
